### ISSUE TITLE
Config settings to toggle copyright 

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#8]
A feature to toggle copyright will be great. 

![copyright](https://user-images.githubusercontent.com/2548160/88487191-dd101580-cf7a-11ea-9dd8-cd3bc5812fd4.png)

**Comment by saowang** [comment]
#### Set up Site Copyright
```yml
author: # default: site.github.owner_name

# copyright: false # default is false

copyright:
  since: false # like: 2000
  revision: false # is show the revision
```

#### Format
```
Copyright [since]-{{ site.time | date: "%Y" }}, [author] Revision [commit]
```
